/*******************************************************************************
 * OLEnemyPriest generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib © 2009-2021 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class OLEnemyPriest extends OLEnemyPawn
    config(Enemy)
    hidecategories(Navigation);

defaultproperties
{
}